name: Update Vulnerability Database

on:
  workflow_dispatch:
  schedule:
    - cron: '42 03 * * MON-FRI' # 03:42 on weekdays, a somewhat random time to avoid producing load spikes on the GH actions infrastructure

env:
  CVE_CACHE_REF: refs/heads/main
  CVE_CACHE_KEY: cve-db
  CVE_CACHE_DIR: ~/.m2/repository/org/owasp/dependency-check-data

jobs:
  update-vulnerability-database:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.CVE_CACHE_REF }}
      - name: Restore Existing Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CVE_CACHE_DIR }}
          key: ${{ env.CVE_CACHE_KEY }}

      - name: Run Maven Plugin
        run: |
          mvn org.owasp:dependency-check-maven:11.1.0:update-only -DnvdApiKey=$NVD_API_KEY -DnvdMaxRetryCount=10 -DnvdApiDelay=15000 -DconnectionTimeout=60000
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Delete Cache
        run: |
          CACHE_IDS=$(gh cache list --key "${{ env.CVE_CACHE_KEY }}" --ref "${{ env.CVE_CACHE_REF }}" --json id | jq -r '.[] | .id')
          for CACHE_ID in $CACHE_IDS; do
              echo "Deleting cache with ID: $CACHE_ID"
              gh cache delete "${CACHE_ID}"
          done
        env:
          GH_TOKEN: ${{ secrets.CLOUD_SDK_AT_SAP_ALL_ACCESS_PAT }}

      - name: Cache CVE Database
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CVE_CACHE_DIR }}
          key: ${{ env.CVE_CACHE_KEY }}

      # - name: "Slack Notification"
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.27.0
      #   with:
      #     payload: |
      #       {
      #         "text": "‚ö†Ô∏è OWASP Update Failed! üò¨ Please inspect & fix by clicking <https://github.com/SAP/ai-sdk-java/actions/runs/${{ github.run_id }}|here>"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


